### ISSUE TITLE
Secure more pictures

### ISSUE THREAD

**Issue by elu267** [elu267/Final_Project#5]

**Comment by OuterHome** [comment]
I will test a download script, and try to run this on our existing model

**Comment by OuterHome** [comment]
I have more pictures from ISIC, but they are all benign image photos, many of which would require more image manipulation to avoid bias. Since we already have too many benign images, I am closing this and will make a task to track artificial image augmentation techniques. If we had some money and official email (for future project improvements), we could buy the dermofit dataset here: https://licensing.eri.ed.ac.uk/i/software/dermofit-image-library.html
